# base URL
server:
  port: 8080
  servlet:
    context-path: /usersys
    multipart:
      max-file-size: 20M
      max-request-size: 20M

# spring
spring:
  resources:
    static-locations: classpath:/static/
  # Mysql data source
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

rabbitmq:
  exchange: business
  queue: log
  url: http://localhost:8081/mq/send/
  redis:
    url: http://localhost:8081/mq/send/redis/list