# base URL

server:
  port: 8082
  servlet:
    context-path: /db
    multipart:
      max-file-size: 20M
      max-request-size: 20M

# spring
spring:
  resources:
    static-locations: classpath:/static/
  # Mysql data source
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: spirng-boot-rabbitmq-sender
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true

rabbitmq:
  exchange: exchange
  queue: topic.message



